export const Users = [
   {
      id:1,
      profilePicture: "/images/person/1.jpg",
      username: "Connor", 
   },
   {
    id:2,
    profilePicture: "/images/person/2.jpg",
    username: "Misael", 
   },
   {
    id:3,
    profilePicture: "/images/person/3.jpg",
    username: "Adan", 
   },
   {
    id:4,
    profilePicture: "/images/person/4.jpg",
    username: "Jimmy", 
   },
   {
    id:5,
    profilePicture: "/images/person/5.jpg",
    username: "Dwayne", 
   },
   {
    id:6,
    profilePicture: "/images/person/6.jpg",
    username: "Kamron", 
   },
   {
    id:7,
    profilePicture: "/images/person/7.jpg",
    username: "Armando", 
   },
   {
    id:8,
    profilePicture: "/images/person/8.jpg",
    username: "Emilie", 
   },
   {
    id:9,
    profilePicture: "/images/person/9.jpg",
    username: "Jaime", 
   },
   {
    id:10,
    profilePicture: "/images/person/10.jpg",
    username: "Julianne", 
   },
];

export const Posts = [
    {
      id:1,
      description: " ",
      photo: "/images/post/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9, 
    },
    {
        id:2,
        description: " ",
        photo: "/images/post/2.jpg",
        date: "5 mins ago",
        userId: 2,
        like: 32,
        comment: 9, 
    },
    {
        id:3,
        description: " ",
        photo: "/images/post/3.jpg",
        date: "5 mins ago",
        userId: 3,
        like: 32,
        comment: 9, 
    },
    {
        id:4,
        description: " ",
        photo: "/images/post/4.jpg",
        date: "5 mins ago",
        userId: 4,
        like: 32,
        comment: 9, 
    },
    {
        id:5,
        description: " ",
        photo: "/images/post/5.jpg",
        date: "5 mins ago",
        userId: 5,
        like: 32,
        comment: 9, 
    },
    {
        id:6,
        description: " ",
        photo: "/images/post/6.jpg",
        date: "5 mins ago",
        userId: 6,
        like: 32,
        comment: 9, 
    },
    {
        id:7,
        description: " ",
        photo: "/images/post/7.jpg",
        date: "5 mins ago",
        userId: 7,
        like: 32,
        comment: 9, 
    },
    {
        id:8,
        description: " ",
        photo: "/images/post/8.jpg",
        date: "5 mins ago",
        userId: 8,
        like: 32,
        comment: 9, 
    },
    {
        id:9,
        description: " ",
        photo: "/images/post/9.jpg",
        date: "5 mins ago",
        userId: 9,
        like: 32,
        comment: 9, 
    },
    {
        id:10,
        description: " ",
        photo: "/images/post/10.jpg",
        date: "5 mins ago",
        userId: 10,
        like: 32,
        comment: 9, 
    },
 ];